[versions]
accompanistSystemuicontroller = "0.27.0"
agp = "8.7.3"
kotlin = "2.1.10"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
dagger = "2.55"
ksp = "2.1.0-1.0.29"
androidXHilt = "1.2.0"
material3WindowSizeClass = "1.3.2"
retrofitVersion = "2.9.0"
roomRuntime = "2.7.2"
runtime = "1.8.3"
roomCommon = "2.7.2"
coilCompose = "2.4.0"
navigationCompose = "2.9.3"
kotlinxSerialization = "1.7.3"
mockkVersion = "1.13.8"
coroutinesVersion = "1.10.1"
turbine = "0.7.0"
materialIconsCore = "1.7.8"
materialIconsExtended = "1.7.8"
core-splashscreen = "1.0.1"
dataStoreVersion = "1.1.7"
barcodeScanning = "17.3.0"
cameraCore = "1.4.2"
kotlinxCoroutinesPlayServices = "1.10.1"
mapsCompose = "2.11.4"
playServicesMaps = "19.2.0"
location = "21.3.0"
zxingAndroidEmbedded = "4.3.0"
firebaseBom = "33.16.0"
services = "4.4.3"
crashlytics = "3.0.5"
performance = "2.0.0"
lottieCompose = "6.6.6"

[libraries]
# Core AndroidX
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanistSystemuicontroller" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-material3-window-size-class1 = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3WindowSizeClass" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
# Lifecycle
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
# Activity y Navigation (Jetpack Compose)
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-navigation-compose ={ group = "androidx.navigation" , name = "navigation-compose", version.ref = "navigationCompose" }
# Compose BOM y UI
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
# Material y Material Icons
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "materialIconsCore" }
androidx-compose-material-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
# Compose runtime
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
# Room
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-room-common = { group = "androidx.room", name = "room-common", version.ref = "roomCommon" }
# Dagger Hilt
google-dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
google-dagger-hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "dagger" }
google-dagger-hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidXHilt" }
# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofitVersion" }
# Coil
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
# KotlinX Serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
# Coroutines
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutinesVersion" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesVersion" }
# Testing
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
# DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStoreVersion" }
# MLKit QR
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
# Camera X
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraCore" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraCore" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraCore" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraCore" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraCore" }
# Maps
kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "mapsCompose" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }
play-services-location = {module = "com.google.android.gms:play-services-location" , version.ref = "location" }
# ZXing
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = {module = "com.google.firebase:firebase-analytics-ktx"}
firebase-realtime-database = { module = "com.google.firebase:firebase-database" }
firebase-perf = {module = "com.google.firebase:firebase-perf-ktx"}
firebase-config = {module = "com.google.firebase:firebase-config-ktx"}
firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-storage = { module = "com.google.firebase:firebase-storage-ktx" }
# Lottie
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
[plugins]
# Basicos
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
# Dagger Hilt
daggerHiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
# Ksp
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
# Kotlinx Serialization
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
# Firebase Google Services
googleServices = { id = "com.google.gms.google-services", version.ref = "services" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
performance = {id = "com.google.firebase.firebase-perf" , version.ref = "performance"}

